// translator.h
// C% to C++ translator — converts AST to C++20 source code using cpct library.
// Reuses the interpreter's Preprocessor, Lexer, Parser to obtain the AST,
// then walks the tree to emit C++ code.
#pragma once
#include "analyzer.h"
#include "../../cpct-interpreter/src/ast.h"
#include "../../cpct-interpreter/src/preprocessor.h"
#include "../../cpct-interpreter/src/lexer.h"
#include "../../cpct-interpreter/src/parser.h"
#include <string>
#include <sstream>
#include <unordered_set>
#include <unordered_map>

class Translator {
public:
    // Translates a C% source string to C++ source string.
    std::string translate(const std::string& cpcSource) {
        // Preprocess → Lex → Parse
        Preprocessor pp;
        std::string processed = pp.process(cpcSource);
        Lexer lexer(processed);
        auto tokens = lexer.tokenize();
        Parser parser(tokens);
        auto program = parser.parse();

        // Static analysis pass (move-after-use detection etc.)
        Analyzer analyzer;
        analyzer.analyze(program);

        // Generate C++ code
        out_.str("");
        out_.clear();
        indent_ = 0;

        // Check if main() exists
        bool hasMain = false;
        for (auto& stmt : program) {
            if (stmt->kind == StmtKind::FuncDecl && stmt->funcName == "main") {
                hasMain = true;
                break;
            }
        }

        emitPreamble();

        if (hasMain) {
            // Main mode: emit function decls and main as-is
            for (auto& stmt : program) {
                translateStmt(stmt.get());
            }
        } else {
            // Script mode: forward-declare functions, then wrap non-func stmts in main()
            // First pass: emit function declarations
            for (auto& stmt : program) {
                if (stmt->kind == StmtKind::FuncDecl) {
                    translateStmt(stmt.get());
                }
            }
            // Second pass: wrap non-func stmts in int main()
            out_ << "int main() {\n";
            indent_++;
            for (auto& stmt : program) {
                if (stmt->kind != StmtKind::FuncDecl) {
                    translateStmt(stmt.get());
                }
            }
            emitIndent(); out_ << "return 0;\n";
            indent_--;
            out_ << "}\n";
        }

        return out_.str();
    }

private:
    std::ostringstream out_;
    int indent_ = 0;
    bool insideMain_ = false;  // true when inside a main() function

    // ============== Preamble / Postamble ==============

    void emitPreamble() {
        out_ << "// Generated by C% Translator\n";
        out_ << "#include <cpct/types.h>\n";
        out_ << "#include <cpct/io.h>\n";
        out_ << "#include <memory>\n";
        out_ << "#include <utility>\n";
        out_ << "using namespace cpct;\n";
        out_ << "\n";
    }

    // (postamble logic is now integrated into translate())

    // ============== Type Mapping ==============

    std::string mapType(const std::string& cpcType) const {
        bool isRef = false;
        std::string base = cpcType;
        if (!base.empty() && base.back() == '@') {
            isRef = true;
            base.pop_back();
        }

        std::string result = mapTypeInner(base);
        if (isRef) result += "&";
        return result;
    }

    std::string mapTypeInner(const std::string& t) const {
        // Scalar types
        if (t == "int")     return "Int";
        if (t == "int8")    return "Int8";
        if (t == "int16")   return "Int16";
        if (t == "int32")   return "Int32";
        if (t == "int64")   return "Int64";
        if (t == "uint")    return "UInt";
        if (t == "uint8")   return "UInt8";
        if (t == "uint16")  return "UInt16";
        if (t == "uint32")  return "UInt32";
        if (t == "uint64")  return "UInt64";
        if (t == "int8f")   return "Int8f";
        if (t == "int16f")  return "Int16f";
        if (t == "int32f")  return "Int32f";
        if (t == "uint8f")  return "UInt8f";
        if (t == "uint16f") return "UInt16f";
        if (t == "uint32f") return "UInt32f";
        if (t == "float" || t == "float64") return "Float";
        if (t == "float32") return "Float32";
        if (t == "string")  return "String";
        if (t == "bool")    return "Bool";
        if (t == "char")    return "Char";
        if (t == "void")    return "void";
        if (t == "intbig" || t == "bigint") return "Int64"; // approximate

        // Array types: "int[]" → "Vector<Int>" (dynamic, since size unknown at translate time)
        if (t.size() > 2 && t.substr(t.size() - 2) == "[]") {
            std::string elem = t.substr(0, t.size() - 2);
            return "Vector<" + mapTypeInner(elem) + ">";
        }

        // vector<T>
        if (t.rfind("vector<", 0) == 0) {
            std::string inner = t.substr(7, t.size() - 8);
            return "Vector<" + mapTypeInner(inner) + ">";
        }

        // array<T>
        if (t.rfind("array<", 0) == 0) {
            std::string inner = t.substr(6, t.size() - 7);
            return "Vector<" + mapTypeInner(inner) + ">";
        }

        // dict
        if (t == "dict") return "Dict";

        // map<K,V>
        if (t.rfind("map<", 0) == 0) {
            std::string inner = t.substr(4, t.size() - 5);
            auto comma = inner.find(',');
            if (comma != std::string::npos) {
                std::string k = inner.substr(0, comma);
                std::string v = inner.substr(comma + 1);
                // trim spaces
                while (!k.empty() && k.back() == ' ') k.pop_back();
                while (!v.empty() && v.front() == ' ') v = v.substr(1);
                return "Map<" + mapTypeInner(k) + ", " + mapTypeInner(v) + ">";
            }
        }

        return t; // unknown, pass through
    }

    // ============== Statement Translation ==============

    void translateStmt(const Stmt* stmt) {
        if (!stmt) return;
        switch (stmt->kind) {
            case StmtKind::VarDecl:   translateVarDecl(stmt); break;
            case StmtKind::ExprStmt:  translateExprStmt(stmt); break;
            case StmtKind::Block:     translateBlock(stmt); break;
            case StmtKind::If:        translateIf(stmt); break;
            case StmtKind::While:     translateWhile(stmt); break;
            case StmtKind::DoWhile:   translateDoWhile(stmt); break;
            case StmtKind::For:       translateFor(stmt); break;
            case StmtKind::ForEach:   translateForEach(stmt); break;
            case StmtKind::ForN:      translateForN(stmt); break;
            case StmtKind::FuncDecl:  translateFuncDecl(stmt); break;
            case StmtKind::Return:    translateReturn(stmt); break;
            case StmtKind::Print:     translatePrint(stmt); break;
            case StmtKind::Break:     emitLine("break;"); break;
            case StmtKind::Continue:  emitLine("continue;"); break;
            case StmtKind::Switch:    translateSwitch(stmt); break;
        }
    }

    void translateVarDecl(const Stmt* stmt) {
        emitIndent();

        bool isArray = !stmt->arrayDimSizes.empty();
        bool isRef = !stmt->varType.empty() && stmt->varType.back() == '@';

        // let → auto with std::move
        if (stmt->isLet) {
            out_ << "auto " << stmt->varName << " = std::move(";
            if (stmt->initExpr) translateExpr(stmt->initExpr.get());
            out_ << ");\n";
            return;
        }

        if (stmt->isStatic) out_ << "static ";
        if (stmt->isConst) out_ << "const ";

        // heap → std::make_unique
        if (stmt->isHeap) {
            std::string base = stmt->varType;
            if (isRef) base.pop_back();
            out_ << "auto " << stmt->varName << " = std::make_unique<" << mapType(base) << ">(";
            if (stmt->initExpr) translateExpr(stmt->initExpr.get());
            out_ << ");\n";
            return;
        }

        // Array declaration
        if (isArray) {
            std::string base = stmt->varType;
            if (isRef) base.pop_back();
            // Strip trailing [] from type name — arrayDimSizes handles dimensions
            while (base.size() >= 2 && base.substr(base.size() - 2) == "[]") {
                base = base.substr(0, base.size() - 2);
            }
            std::string cppElem = mapTypeInner(base);

            int dims = static_cast<int>(stmt->arrayDimSizes.size());
            if (dims == 1 && stmt->arrayDimSizes[0]) {
                // Fixed size 1D: Array<T, N>
                out_ << "Array<" << cppElem << ", ";
                translateExpr(stmt->arrayDimSizes[0].get());
                out_ << "> " << stmt->varName;
            } else if (dims == 1) {
                // Size inferred 1D
                out_ << "Vector<" << cppElem << "> " << stmt->varName;
            } else {
                // Multi-dimensional: nest Vector<Vector<...>>
                std::string type = cppElem;
                for (int d = 0; d < dims; d++) {
                    type = "Vector<" + type + ">";
                }
                out_ << type << " " << stmt->varName;
            }

            if (stmt->initExpr) {
                out_ << " = ";
                translateExpr(stmt->initExpr.get());
            }
            out_ << ";\n";
            return;
        }

        // Dict with DictLiteral init → emit set() calls
        if (stmt->varType == "dict" && stmt->initExpr &&
            stmt->initExpr->kind == ExprKind::DictLiteral) {
            out_ << "Dict " << stmt->varName << ";\n";
            auto* init = stmt->initExpr.get();
            for (size_t i = 0; i < init->elements.size(); i++) {
                emitIndent();
                out_ << stmt->varName << ".set(";
                translateExpr(init->elements[i].get());
                out_ << ", ";
                translateExpr(init->dictValues[i].get());
                out_ << ");\n";
            }
            return;
        }

        // Map with DictLiteral init → emit set() calls
        if (stmt->varType.rfind("map<", 0) == 0 && stmt->initExpr &&
            stmt->initExpr->kind == ExprKind::DictLiteral) {
            out_ << mapType(stmt->varType) << " " << stmt->varName << ";\n";
            auto* init = stmt->initExpr.get();
            for (size_t i = 0; i < init->elements.size(); i++) {
                emitIndent();
                out_ << stmt->varName << ".set(";
                translateExpr(init->elements[i].get());
                out_ << ", ";
                translateExpr(init->dictValues[i].get());
                out_ << ");\n";
            }
            return;
        }

        // Regular variable
        out_ << mapType(stmt->varType) << " " << stmt->varName;
        if (stmt->initExpr) {
            out_ << " = ";
            translateExpr(stmt->initExpr.get());
        }
        out_ << ";\n";
    }

    void translateExprStmt(const Stmt* stmt) {
        emitIndent();
        translateExpr(stmt->expr.get());
        out_ << ";\n";
    }

    void translateBlock(const Stmt* stmt) {
        emitIndent(); out_ << "{\n";
        indent_++;
        for (auto& s : stmt->body) translateStmt(s.get());
        indent_--;
        emitIndent(); out_ << "}\n";
    }

    void translateIf(const Stmt* stmt) {
        emitIndent();
        out_ << "if (";
        translateExpr(stmt->condition.get());
        out_ << ") ";
        translateBody(stmt->thenBranch.get());
        if (stmt->elseBranch) {
            emitIndent();
            out_ << "else ";
            if (stmt->elseBranch->kind == StmtKind::If) {
                // else if
                translateIf(stmt->elseBranch.get());
            } else {
                translateBody(stmt->elseBranch.get());
            }
        }
    }

    void translateWhile(const Stmt* stmt) {
        emitIndent();
        out_ << "while (";
        translateExpr(stmt->condition.get());
        out_ << ") ";
        translateBody(stmt->thenBranch.get());
    }

    void translateDoWhile(const Stmt* stmt) {
        emitIndent();
        out_ << "do ";
        translateBody(stmt->thenBranch.get());
        emitIndent();
        out_ << "while (";
        translateExpr(stmt->condition.get());
        out_ << ");\n";
    }

    void translateFor(const Stmt* stmt) {
        emitIndent();
        out_ << "for (";
        // init — emit without indent/newline
        if (stmt->initStmt) {
            if (stmt->initStmt->kind == StmtKind::VarDecl) {
                auto* s = stmt->initStmt.get();
                out_ << mapType(s->varType) << " " << s->varName;
                if (s->initExpr) {
                    out_ << " = ";
                    translateExpr(s->initExpr.get());
                }
            }
        }
        out_ << "; ";
        if (stmt->condition) translateExpr(stmt->condition.get());
        out_ << "; ";
        if (stmt->increment) translateExpr(stmt->increment.get());
        out_ << ") ";
        translateBody(stmt->thenBranch.get());
    }

    void translateForEach(const Stmt* stmt) {
        emitIndent();
        out_ << "for (";
        if (!stmt->varType.empty()) {
            out_ << mapType(stmt->varType) << " ";
        } else {
            out_ << "auto ";
        }
        out_ << stmt->varName << " : ";
        translateExpr(stmt->expr.get());
        out_ << ") ";
        translateBody(stmt->thenBranch.get());
    }

    void translateForN(const Stmt* stmt) {
        emitIndent();
        out_ << "for (int _i = 0; _i < ";
        translateExpr(stmt->expr.get());
        out_ << "; _i++) ";
        translateBody(stmt->thenBranch.get());
    }

    void translateFuncDecl(const Stmt* stmt) {
        out_ << "\n";
        emitIndent();
        // main() must return int in C++
        if (stmt->funcName == "main") {
            out_ << "int main(";
        } else {
            out_ << mapType(stmt->funcReturnType) << " " << stmt->funcName << "(";
        }
        for (size_t i = 0; i < stmt->params.size(); i++) {
            if (i > 0) out_ << ", ";
            auto& p = stmt->params[i];
            std::string ptype = mapType(p.type);
            if (p.isRef && ptype.back() != '&') ptype += "&";
            out_ << ptype << " " << p.name;
        }
        out_ << ") {\n";
        indent_++;
        for (auto& s : stmt->body) translateStmt(s.get());
        indent_--;
        emitIndent(); out_ << "}\n";
    }

    void translateReturn(const Stmt* stmt) {
        emitIndent();
        out_ << "return";
        if (stmt->expr) {
            out_ << " ";
            translateExpr(stmt->expr.get());
        }
        out_ << ";\n";
    }

    void translatePrint(const Stmt* stmt) {
        emitIndent();
        if (stmt->printNewline) {
            out_ << "println(";
        } else {
            out_ << "print(";
        }
        for (size_t i = 0; i < stmt->printArgs.size(); i++) {
            if (i > 0) out_ << ", ";
            translateExpr(stmt->printArgs[i].get());
        }
        out_ << ");\n";
    }

    void translateSwitch(const Stmt* stmt) {
        // Check if any case value is a string literal → use if-else chain
        bool hasStringCase = false;
        for (auto& cv : stmt->caseValues) {
            if (cv && cv->kind == ExprKind::StringLiteral) {
                hasStringCase = true;
                break;
            }
        }

        if (hasStringCase) {
            // String switch → if-else chain
            emitIndent();
            out_ << "{\n";
            indent_++;
            emitIndent();
            out_ << "auto _sw = ";
            translateExpr(stmt->condition.get());
            out_ << ";\n";

            bool first = true;
            for (size_t i = 0; i < stmt->caseValues.size(); i++) {
                emitIndent();
                if (stmt->caseValues[i]) {
                    if (first) { out_ << "if"; first = false; }
                    else out_ << "else if";
                    out_ << " (_sw == ";
                    translateExpr(stmt->caseValues[i].get());
                    out_ << ") {\n";
                } else {
                    out_ << "else {\n";
                }
                indent_++;
                for (auto& s : stmt->caseBodies[i]) {
                    // Skip break statements in if-else conversion
                    if (s->kind != StmtKind::Break) translateStmt(s.get());
                }
                indent_--;
                emitIndent(); out_ << "}\n";
            }
            indent_--;
            emitIndent(); out_ << "}\n";
        } else {
            // Integer switch → native C++ switch
            emitIndent();
            out_ << "switch (static_cast<int>(";
            translateExpr(stmt->condition.get());
            out_ << ")) {\n";
            indent_++;
            for (size_t i = 0; i < stmt->caseValues.size(); i++) {
                emitIndent();
                if (stmt->caseValues[i]) {
                    out_ << "case ";
                    translateExpr(stmt->caseValues[i].get());
                    out_ << ":\n";
                } else {
                    out_ << "default:\n";
                }
                indent_++;
                for (auto& s : stmt->caseBodies[i]) translateStmt(s.get());
                indent_--;
            }
            indent_--;
            emitIndent(); out_ << "}\n";
        }
    }

    // ============== Expression Translation ==============

    void translateExpr(const Expr* expr) {
        if (!expr) return;
        switch (expr->kind) {
            case ExprKind::IntLiteral:
                out_ << expr->intVal;
                break;
            case ExprKind::FloatLiteral:
                out_ << expr->floatVal;
                break;
            case ExprKind::StringLiteral:
                out_ << "\"" << escapeString(expr->strVal) << "\"";
                break;
            case ExprKind::CharLiteral:
                out_ << "'" << escapeChar(static_cast<char>(expr->intVal)) << "'";
                break;
            case ExprKind::BoolLiteral:
                out_ << (expr->boolVal ? "true" : "false");
                break;
            case ExprKind::BigIntLiteral:
                out_ << expr->strVal << "LL";
                break;
            case ExprKind::Identifier:
                out_ << expr->name;
                break;
            case ExprKind::BinaryOp:
                translateBinaryOp(expr);
                break;
            case ExprKind::UnaryOp:
                out_ << mapOperator(expr->op);
                translateExpr(expr->operand.get());
                break;
            case ExprKind::Assign:
                out_ << expr->name << " = ";
                translateExpr(expr->right.get());
                break;
            case ExprKind::CompoundAssign:
                out_ << expr->name << " " << mapCompoundOp(expr->op) << " ";
                translateExpr(expr->right.get());
                break;
            case ExprKind::PreIncrement:
                out_ << "++";
                translateExpr(expr->operand.get());
                break;
            case ExprKind::PreDecrement:
                out_ << "--";
                translateExpr(expr->operand.get());
                break;
            case ExprKind::PostIncrement:
                translateExpr(expr->operand.get());
                out_ << "++";
                break;
            case ExprKind::PostDecrement:
                translateExpr(expr->operand.get());
                out_ << "--";
                break;
            case ExprKind::FunctionCall:
                translateFunctionCall(expr);
                break;
            case ExprKind::ArrayAccess:
                translateExpr(expr->arrayExpr.get());
                out_ << "[";
                translateExpr(expr->indexExpr.get());
                out_ << "]";
                break;
            case ExprKind::ArrayAssign:
                translateExpr(expr->arrayExpr.get());
                out_ << "[";
                translateExpr(expr->indexExpr.get());
                out_ << "] = ";
                translateExpr(expr->right.get());
                break;
            case ExprKind::ArrayCompoundAssign:
                translateExpr(expr->arrayExpr.get());
                out_ << "[";
                translateExpr(expr->indexExpr.get());
                out_ << "] " << mapCompoundOp(expr->op) << " ";
                translateExpr(expr->right.get());
                break;
            case ExprKind::ArraySlice:
                translateExpr(expr->arrayExpr.get());
                out_ << ".slice(";
                translateExpr(expr->indexExpr.get());
                out_ << ", ";
                translateExpr(expr->endIndexExpr.get());
                out_ << ")";
                break;
            case ExprKind::ArrayLiteral:
                out_ << "{";
                for (size_t i = 0; i < expr->elements.size(); i++) {
                    if (i > 0) out_ << ", ";
                    translateExpr(expr->elements[i].get());
                }
                out_ << "}";
                break;
            case ExprKind::DictLiteral:
                // Dict/Map initialization — emit as initializer list
                out_ << "{";
                for (size_t i = 0; i < expr->elements.size(); i++) {
                    if (i > 0) out_ << ", ";
                    out_ << "{";
                    translateExpr(expr->elements[i].get());
                    out_ << ", ";
                    translateExpr(expr->dictValues[i].get());
                    out_ << "}";
                }
                out_ << "}";
                break;
            case ExprKind::FStringExpr:
                out_ << "cpct::format(";
                for (size_t i = 0; i < expr->elements.size(); i++) {
                    if (i > 0) out_ << ", ";
                    translateExpr(expr->elements[i].get());
                }
                out_ << ")";
                break;
            case ExprKind::Input:
                out_ << "cpct::input()";
                break;
            case ExprKind::ChainedComparison:
                translateChainedComparison(expr);
                break;
            case ExprKind::Ternary:
                out_ << "(";
                translateExpr(expr->operand.get()); // condition
                out_ << " ? ";
                translateExpr(expr->left.get());    // true
                out_ << " : ";
                translateExpr(expr->right.get());   // false
                out_ << ")";
                break;
            case ExprKind::RefArg:
                out_ << expr->name; // ref drops in C++
                break;
            case ExprKind::LetArg:
                out_ << "std::move(" << expr->name << ")";
                break;
        }
    }

    void translateBinaryOp(const Expr* expr) {
        if (expr->op == TokenType::POWER) {
            out_ << "cpct::pow(";
            translateExpr(expr->left.get());
            out_ << ", ";
            translateExpr(expr->right.get());
            out_ << ")";
        } else if (expr->op == TokenType::DIVMOD) {
            out_ << "cpct::divmod(";
            translateExpr(expr->left.get());
            out_ << ", ";
            translateExpr(expr->right.get());
            out_ << ")";
        } else if (expr->op == TokenType::PLUS &&
                   expr->left->kind == ExprKind::StringLiteral) {
            // "literal" + x → String("literal") + x (const char* + can't use operator+)
            out_ << "(String(\"" << escapeString(expr->left->strVal) << "\") + ";
            translateExpr(expr->right.get());
            out_ << ")";
        } else if (isComparisonOp(expr->op)) {
            // Safe comparison using std::cmp_* (handles signed/unsigned correctly)
            out_ << mapCmpFunc(expr->op) << "(";
            translateExpr(expr->left.get());
            out_ << ", ";
            translateExpr(expr->right.get());
            out_ << ")";
        } else {
            out_ << "(";
            translateExpr(expr->left.get());
            out_ << " " << mapOperator(expr->op) << " ";
            translateExpr(expr->right.get());
            out_ << ")";
        }
    }

    void translateChainedComparison(const Expr* expr) {
        // a < b < c → (std::cmp_less(a, b) && std::cmp_less(b, c))
        out_ << "(";
        for (size_t i = 0; i < expr->chainOps.size(); i++) {
            if (i > 0) out_ << " && ";
            out_ << mapCmpFunc(expr->chainOps[i]) << "(";
            translateExpr(expr->chainOperands[i].get());
            out_ << ", ";
            translateExpr(expr->chainOperands[i + 1].get());
            out_ << ")";
        }
        out_ << ")";
    }

    void translateFunctionCall(const Expr* expr) {
        const std::string& name = expr->funcName;

        // Built-in type casts: int(x) → to_int(x)
        static const std::unordered_set<std::string> castFuncs = {
            "int", "int8", "int16", "int32", "int64",
            "uint", "uint8", "uint16", "uint32", "uint64",
            "float", "float32", "float64",
            "string", "bool", "char"
        };
        if (castFuncs.count(name)) {
            out_ << "to_" << name << "(";
            for (size_t i = 0; i < expr->args.size(); i++) {
                if (i > 0) out_ << ", ";
                translateExpr(expr->args[i].get());
            }
            out_ << ")";
            return;
        }

        // Built-in functions that map to methods
        static const std::unordered_set<std::string> methodFuncs = {
            "len", "size", "type", "push", "pop", "insert", "erase",
            "clear", "front", "back", "is_empty", "has", "keys", "values",
            "remove", "sort", "sortkey", "sortk", "sortval", "sortv", "sortvk",
            "reverse", "find", "is_contains", "shape",
            "upper", "lower", "trim", "replace", "split", "substr",
            "is_starts_with", "is_ends_with", "is_digit", "is_alpha",
            "is_upper", "is_lower"
        };

        // Method-style call: already desugared by parser as func(obj, args...)
        // Check if first arg could be the "self" and function is a known method
        if (methodFuncs.count(name) && !expr->args.empty()) {
            auto* firstArg = expr->args[0].get();
            bool isLiteral = firstArg->kind == ExprKind::IntLiteral ||
                             firstArg->kind == ExprKind::FloatLiteral ||
                             firstArg->kind == ExprKind::StringLiteral ||
                             firstArg->kind == ExprKind::CharLiteral ||
                             firstArg->kind == ExprKind::BoolLiteral;
            if (isLiteral) {
                // Wrap literal: "hello" → String("hello"), 3.14 → Float(3.14)
                wrapLiteral(firstArg);
            } else {
                translateExpr(firstArg);
            }
            out_ << "." << name << "(";
            for (size_t i = 1; i < expr->args.size(); i++) {
                if (i > 1) out_ << ", ";
                // sort/sortkey/sortval/sortvk: "desc" → true, "asc" → false
                if ((name == "sort" || name == "sortkey" || name == "sortk" ||
                     name == "sortval" || name == "sortv" || name == "sortvk") &&
                    expr->args[i]->kind == ExprKind::StringLiteral) {
                    out_ << (expr->args[i]->strVal == "desc" ? "true" : "false");
                } else {
                    translateExpr(expr->args[i].get());
                }
            }
            out_ << ")";
            return;
        }

        // print/println — handled by StmtKind::Print, but can appear as expression
        if (name == "print" || name == "println") {
            out_ << name << "(";
            for (size_t i = 0; i < expr->args.size(); i++) {
                if (i > 0) out_ << ", ";
                translateExpr(expr->args[i].get());
            }
            out_ << ")";
            return;
        }

        // input
        if (name == "input") {
            out_ << "cpct::input(";
            for (size_t i = 0; i < expr->args.size(); i++) {
                if (i > 0) out_ << ", ";
                translateExpr(expr->args[i].get());
            }
            out_ << ")";
            return;
        }

        // divmod as free function
        if (name == "divmod") {
            out_ << "cpct::divmod(";
            for (size_t i = 0; i < expr->args.size(); i++) {
                if (i > 0) out_ << ", ";
                translateExpr(expr->args[i].get());
            }
            out_ << ")";
            return;
        }

        // Default: user-defined function
        out_ << name << "(";
        for (size_t i = 0; i < expr->args.size(); i++) {
            if (i > 0) out_ << ", ";
            translateExpr(expr->args[i].get());
        }
        out_ << ")";
    }

    // ============== Operator Mapping ==============

    std::string mapOperator(TokenType op) const {
        switch (op) {
            case TokenType::PLUS: return "+";
            case TokenType::MINUS: return "-";
            case TokenType::STAR: return "*";
            case TokenType::SLASH: return "/";
            case TokenType::PERCENT: return "%";
            case TokenType::ASSIGN: return "=";
            case TokenType::EQ: return "==";
            case TokenType::NEQ: return "!=";
            case TokenType::LT: return "<";
            case TokenType::GT: return ">";
            case TokenType::LTE: return "<=";
            case TokenType::GTE: return ">=";
            case TokenType::AND: return "&&";
            case TokenType::OR: return "||";
            case TokenType::NOT: return "!";
            case TokenType::BIT_AND: return "&";
            case TokenType::BIT_OR: return "|";
            case TokenType::BIT_XOR: return "^";
            case TokenType::BIT_NOT: return "~";
            case TokenType::LSHIFT: return "<<";
            case TokenType::RSHIFT: return ">>";
            default: return "/* ?? */";
        }
    }

    std::string mapCompoundOp(TokenType op) const {
        switch (op) {
            case TokenType::PLUS_ASSIGN: return "+=";
            case TokenType::MINUS_ASSIGN: return "-=";
            case TokenType::STAR_ASSIGN: return "*=";
            case TokenType::SLASH_ASSIGN: return "/=";
            case TokenType::PERCENT_ASSIGN: return "%=";
            case TokenType::BIT_AND_ASSIGN: return "&=";
            case TokenType::BIT_OR_ASSIGN: return "|=";
            case TokenType::BIT_XOR_ASSIGN: return "^=";
            case TokenType::LSHIFT_ASSIGN: return "<<=";
            case TokenType::RSHIFT_ASSIGN: return ">>=";
            default: return "/* unknown= */";
        }
    }

    // ============== Comparison Helpers ==============

    static bool isComparisonOp(TokenType op) {
        return op == TokenType::LT || op == TokenType::GT ||
               op == TokenType::LTE || op == TokenType::GTE ||
               op == TokenType::EQ || op == TokenType::NEQ;
    }

    static std::string mapCmpFunc(TokenType op) {
        switch (op) {
            case TokenType::LT:  return "cpct::cmp_less";
            case TokenType::GT:  return "cpct::cmp_greater";
            case TokenType::LTE: return "cpct::cmp_less_equal";
            case TokenType::GTE: return "cpct::cmp_greater_equal";
            case TokenType::EQ:  return "cpct::cmp_equal";
            case TokenType::NEQ: return "cpct::cmp_not_equal";
            default: return "/* unknown cmp */";
        }
    }

    // ============== Helpers ==============

    void translateBody(const Stmt* stmt) {
        if (stmt->kind == StmtKind::Block) {
            out_ << "{\n";
            indent_++;
            for (auto& s : stmt->body) translateStmt(s.get());
            indent_--;
            emitIndent(); out_ << "}\n";
        } else {
            out_ << "{\n";
            indent_++;
            translateStmt(stmt);
            indent_--;
            emitIndent(); out_ << "}\n";
        }
    }

    void emitIndent() {
        for (int i = 0; i < indent_; i++) out_ << "    ";
    }

    void emitLine(const std::string& line) {
        emitIndent();
        out_ << line << "\n";
    }

    // Wraps a literal expression in its cpct type constructor for method calls
    void wrapLiteral(const Expr* expr) {
        switch (expr->kind) {
            case ExprKind::StringLiteral:
                out_ << "String(\"" << escapeString(expr->strVal) << "\")";
                break;
            case ExprKind::IntLiteral:
                out_ << "Int(" << expr->intVal << ")";
                break;
            case ExprKind::FloatLiteral:
                out_ << "Float(" << expr->floatVal << ")";
                break;
            case ExprKind::CharLiteral:
                out_ << "Char('" << escapeChar(static_cast<char>(expr->intVal)) << "')";
                break;
            case ExprKind::BoolLiteral:
                out_ << "Bool(" << (expr->boolVal ? "true" : "false") << ")";
                break;
            default:
                translateExpr(expr);
                break;
        }
    }

    static std::string escapeString(const std::string& s) {
        std::string r;
        for (char c : s) {
            switch (c) {
                case '\\': r += "\\\\"; break;
                case '"':  r += "\\\""; break;
                case '\n': r += "\\n"; break;
                case '\t': r += "\\t"; break;
                default:   r += c; break;
            }
        }
        return r;
    }

    static std::string escapeChar(char c) {
        switch (c) {
            case '\\': return "\\\\";
            case '\'': return "\\'";
            case '\n': return "\\n";
            case '\t': return "\\t";
            case '\0': return "\\0";
            default: return std::string(1, c);
        }
    }
};
